web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack

    get "/", TopicController, :index, as: :root
    resources "/topics", TopicController

  end

  scope "/auth", Discuss do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
end

lib/discuss/endpoint.ex
defmodule Discuss.Endpoint do
  use Phoenix.Endpoint, otp_app: :discuss

  socket "/socket", Discuss.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :discuss, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_discuss_key",
    signing_salt: "zk/nhgue"

  plug Discuss.Router
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo, otp_app: :discuss
end

web/models/topic.ex
defmodule Discuss.Topic do
  @moduledoc """
  Topic model
  """

  use Discuss.Web, :model

  alias Discuss.Topic

  schema "topics" do
    field :title, :string
  end

  @doc """
  Changes a Map of data into a Changset for Topic
  """
  def changeset(%Topic{} = struct, params \\ %{}) do
    struct
    |> cast(params, [:title])
    |> validate_required([:title])
  end

end

web/models/user.ex
defmodule Discuss.User do
  @moduledoc """
  Represents a user schema
  """
  use Discuss.Web, :model

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string

    timestamps
  end

  @required [:email, :provider, :token]

  def changeset(user, params \\ %{}) do
    user
    |> cast(params, @required)
    |> validate_required(@required)
  end
end

web/controllers/auth_controller.ex
defmodule Discuss.AuthController do
  use Discuss.Web, :controller
  plug Ueberauth

  alias Discuss.{User, Repo}
  alias Plug.Conn

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    user_params = %{token: auth.credentials.token, email: auth.info.email,
     provider: to_string(auth.provider)}

    user_cs = User.changeset(%User{}, user_params)
    signin(conn, user_cs)
  end

  def signout(conn, _parms) do
    conn
    |> Conn.configure_session(drop: true)
    |> redirect(to: topic_path(conn, :index))
  end

  defp signin(conn, user_cs) do
    case insert_or_update_user(user_cs) do
      {:error, _reason} ->
        conn
        |> put_flash(:error, 'Could not login')
        |> redirect(to: root_path(conn, :index))
      {:ok, user} ->
        conn
        |> put_session(:user_id, user.id)
        |> put_flash(:info, "Login successfull")
        |> redirect(to: root_path(conn, :index))
    end
  end

  defp insert_or_update_user(user_cs) do
    case Repo.get_by(User, email: user_cs.changes.email) do
      nil ->
        Repo.insert(user_cs)
      user ->
        {:ok, user}
    end
  end
end

web/controllers/topic_controller.ex
defmodule Discuss.TopicController do
  use Discuss.Web, :controller
  plug Discuss.IsAuthenticated when action in [:new, :create, :edit, :update, :delete]

  alias Discuss.{Topic, Repo}

  def index(conn, _params) do
    render conn, topics: Repo.all(Topic), changeset: Topic.changeset(%Topic{})
  end

  def new(conn, _params) do
    changeset = Topic.changeset %Topic{}, %{}
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"topic" => topic}) do
    cs = Topic.changeset %Topic{}, topic
    case Repo.insert(cs) do
      {:error, cs} ->
        render conn, "new.html", changeset: cs
      {:ok, topic} ->
        redirect conn, to: topic_path(conn, :show, topic)
    end
  end

  def edit(conn, %{"id" => id}) do
    case Repo.get(Topic, id) do
      nil ->
        conn
        |> put_flash(:error, "Topic with id of #{id} could not be found")
        |> redirect(to: topic_path(conn, :index))
      topic ->
        render conn, "edit.html", changeset: Topic.changeset(topic), topic: topic
    end
  end

  def update(conn, %{"id" => id, "topic" => topic_params}) do
    topic = Repo.get(Topic, id)
    changeset = Topic.changeset(topic, topic_params)

    case Repo.update(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic updated!")
        |> redirect(to: topic_path(conn, :index))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Unable to update Topic")
        |> render("edit.html", changeset: changeset, topic: topic)
    end
  end

  def show(conn, %{"id" => id}) do
    case Repo.get(Topic, id) do
      nil ->
        redirect conn, to: topic_path(conn, :new)
      topic ->
        render conn, "show.html", topic: topic
    end
  end

  def delete(conn, %{"id" => id}) do
    topic = Repo.get(Topic, id)
    case Repo.delete(topic) do
      {:error, _cs} ->
        put_flash(conn, :flash, "Unable to remove topic with id #{id}")
        redirect conn, to: topic_path(conn, :index)
      {:ok, topic} ->
        put_flash(conn, :flash, "Topic #{topic.title} has been deleted")
        redirect conn, to: topic_path(conn, :index)
    end
  end
end

web/views/error_view.ex
defmodule Discuss.ErrorView do
  use Discuss.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

web/views/topic_view.ex
defmodule Discuss.TopicView do
  use Discuss.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc=" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">Discussions</a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li><%= link 'Logout', to: auth_path(@conn, :signout) %></li>
          <% else %>
            <li><%= link 'Sign in with github', to: auth_path(@conn, :request, :github)  %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/topic/_topic_form.html.eex
<%= form_for @changeset, @path, @opts, fn f -> %>

  <div class="form-group">
    <%= text_input(f, :title, placeholder: "Title", class: "form-control") %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Submit", class: "btn btn-primary" %>
<% end %>

web/templates/topic/edit.html.eex
<h2>Edit a topic</h2>

<p>
  <%= link("Show Topics", to: topic_path(@conn, :index)) %>
</p>

<%= render "_topic_form.html",
  path: topic_path(@conn, :update, @topic),
  opts: [method: :patch],
  changeset: @changeset %>

web/templates/topic/index.html.eex
<h3>Index of topics</h3>

<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

<table>
<%= for topic <- @topics do %>
  <tr>
    <td><%= link topic.title, to: topic_path(@conn, :show, topic.id) %></td>
    <td>
      <%= button "Edit", to: topic_path(@conn, :edit, topic.id), method: :get %>
      <%= button "Delete", to: topic_path(@conn, :delete, topic.id), method: :delete %>
    </td>
</tr>
<% end %>
</table>

web/templates/topic/new.html.eex
<h2>Add a topic</h2>

<p>
  <%= link("Show Topics", to: topic_path(@conn, :index)) %>
</p>

<%= render "_topic_form.html",
  path: topic_path(@conn, :create),
  opts: [],
  changeset: @changeset %>

web/templates/topic/show.html.eex
<h2>Topic</h2>

<p>
  <%= link("Show Topics", to: topic_path(@conn, :show, @topic.id)) %>
  <%= link("Edit Topic", to: topic_path(@conn, :edit, @topic.id)) %>
  <%= link("New Topic", to: topic_path(@conn, :new)) %>
</p>

<%= @topic.title  %>